_BASE_: "densepose_rcnn_R_101_FPN_s1x_legacy.yaml"
images_dir:
  Name: "/home/visier/mm_fi/MMFi_dataset/all_images"

MODEL_NAME: 
  Name: "WiFi_DensePose"

Teacher_Model:
  NAME: "MyGeneralizedRCNN"

MTN:
  NAME: "ModalityTranslationNetwork"

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.01
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  WARMUP_FACTOR: 0.1

MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/densepose/densepose_rcnn_R_101_FPN_s1x_legacy/164832182/model_final_10af0e.pkl" 
loss:
  densepose: 0.6
  cls: 1.2
  box: 1.0
  transfer: 0.001

Student: 
  Resume: 'output/checkpoint_0000005.pth'
  save_interval: 50
INPUT:
  MIN_SIZE_TEST: 480
  MAX_SIZE_TEST: 640